In [1]:
!pip install pyarrow fastparquet

Requirement already satisfied: pyarrow in c:\users\treye\anaconda3\lib\site-packages (14.0.2)
Requirement already satisfied: fastparquet in c:\users\treye\anaconda3\lib\site-packages (2025.12.0)
Requirement already satisfied: numpy>=1.16.6 in c:\users\treye\anaconda3\lib\site-packages (from pyarrow) (1.26.4)
Requirement already satisfied: pandas>=1.5.0 in c:\users\treye\anaconda3\lib\site-packages (from fastparquet) (2.3.3)
Requirement already satisfied: cramjam>=2.3 in c:\users\treye\anaconda3\lib\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in c:\users\treye\anaconda3\lib\site-packages (from fastparquet) (2023.10.0)
Requirement already satisfied: packaging in c:\users\treye\anaconda3\lib\site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\treye\anaconda3\lib\site-packages (from pandas>=1.5.0->fastparquet) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\treye\anaconda3\lib\site-packages (from pandas>=1.5.0->fastparquet) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\treye\anaconda3\lib\site-packages (from pandas>=1.5.0->fastparquet) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\treye\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.16.0)

In [2]:
import pandas as pd
import numpy as np

In [132]:
events = pd.read_parquet("C:/Users/treye/Downloads/events.parquet")
stints = pd.read_parquet("C:/Users/treye/Downloads/stints.parquet")
games = pd.read_parquet("C:/Users/treye/Downloads/games.parquet")
players = pd.read_parquet("C:/Users/treye/Downloads/players.parquet")
tracking = pd.read_parquet("C:/Users/treye/Downloads/tracking.parquet")

In [133]:
pd.set_option('display.max_columns', None)

In [134]:
events["dzone"] = (events["x_adj"] < -25.0).astype(int)
events["nzone"] = ((events["x_adj"] >= -25.0) & (events["x_adj"] <= 25.0)).astype(int)
events["ozone"] = (events["x_adj"] > 25.0).astype(int)
events["poss_team"] = events["team"]


g = events.groupby(["game_id", "sequence_id"])

events["prev_dzone"] = g["dzone"].shift(1)
events["prev_team"] = g["poss_team"].shift(1)
events["prev_nzone"] = g["nzone"].shift(1)
events["prev_ozone"] = g["ozone"].shift(1)
events["next_team"] = g["poss_team"].shift(-1)

events["lpr_poss_start"] = (
    (events["event_type"] == "lpr") &
    (events["poss_team"] != events["prev_team"])
).astype(int)

events["poss_id"] = (
    events
    .groupby("game_id")["lpr_poss_start"]
    .cumsum()
)

events["dz_poss_start"] = (
    (events["lpr_poss_start"] == 1) &
    (events["dzone"] == 1)
).astype(int)

In [138]:
events["dz_start_possession"] = events.groupby("poss_id")["dz_poss_start"].transform("max")

# 3 outcomes for and end (first and last are considered successes for getting puck out, second is a failure)
events["controlled_exit"] = ((events["dz_start_possession"]==1)&(events["dzone"]==0) & (events["prev_dzone"]==1) & (events["poss_team"]==events["prev_team"])).astype(int)
events["dz_turnover"] = ((events["dz_start_possession"]==1)&(events["event_type"]=="lpr") & (events["prev_dzone"]==1) & (events["ozone"]==1) & (events["poss_team"]!=events["prev_team"])).astype(int)
events["leave_dz_without_puck"] = ((events["dz_start_possession"]==1)&(events["ozone"]==0)&(events["prev_dzone"]==1)&(events["poss_team"]!=events["prev_team"])&(events["event_type"]=="lpr")).astype(int)

In [139]:
events.head(60)

,game_id,period,period_time,game_stint,sl_event_id,sequence_id,player_id,player_name,team,team_id,opp_team,opp_team_id,event_type,outcome,flags,description,detail,sl_xg_all_shots,x,y,x_adj,y_adj,has_tracking_data,event_player_tracked,dzone,nzone,ozone,poss_team,prev_dzone,prev_team,prev_nzone,prev_ozone,next_team,lpr_poss_start,poss_id,dz_poss_start,dz_start_possession,controlled_exit,dz_turnover,leave_dz_without_puck
0,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,0,1,None,None,None,None,None,None,faceoff,None,None,Face-Off,nz,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,NaN,NaN,NaN,NaN,GR,0,0,0,0,0,0,0
1,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,1,1,8cdcb61e-d733-bde6-a101-ef3140e48149,"L'Esperance, Joel",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,faceoff,failed,"centerfodot, righthandedopponent",NZ FACE OFF-,none,NaN,-0.201431,-0.755550,-0.201431,-0.755550,1,1,0,1,0,GR,0.0,None,0.0,0.0,CLE,0,0,0,0,0,0,0
2,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,2,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,faceoff,successful,"centerfodot, righthandedopponent",NZ REC FACE OFF+ENTRY,recoveredwithentry,NaN,-0.201431,-0.755550,0.201431,0.755550,1,1,0,1,0,CLE,0.0,GR,1.0,0.0,CLE,0,0,0,0,0,0,0
3,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.070000000,1.0,3,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,None,F/OFF LPR+ NZ,faceoff,NaN,0.807243,1.257381,-0.807243,-1.257381,1,1,0,1,0,CLE,0.0,CLE,1.0,0.0,CLE,0,0,0,0,0,0,0
4,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.130000000,1.0,4,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,NZPASS south+,south,NaN,0.304306,0.845894,-0.304306,-0.845894,1,1,0,1,0,CLE,0.0,CLE,1.0,0.0,CLE,0,0,0,0,0,0,0
5,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,2.200000000,1.0,5,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,6.339600,20.917810,-6.339600,-20.917810,1,1,0,1,0,CLE,0.0,CLE,1.0,0.0,CLE,0,0,0,0,0,0,0
6,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,2.470000000,1.0,6,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,NZPASS north+,north,NaN,6.339600,23.386793,-6.339600,-23.386793,1,1,0,1,0,CLE,0.0,CLE,1.0,0.0,CLE,0,0,0,0,0,0,0
7,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,3.370000000,1.0,7,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,-23.839119,20.872547,23.839119,-20.872547,1,1,0,1,0,CLE,0.0,CLE,1.0,0.0,CLE,0,0,0,0,0,0,0
8,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,4.430000000,1.0,8,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,failed,eastwest,NORTH CYCLE OFFBOARDS-,northoffboards,NaN,-43.451580,25.992952,43.451580,-25.992952,1,1,0,0,1,CLE,0.0,CLE,1.0,0.0,CLE,0,0,0,0,0,0,0
9,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,7.130000000,1.0,9,1,0f052c34-6cd2-f4fd-a861-d9051a8e86e4,"Angle, Tyler",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,failed,None,MISS PASS,regular,NaN,-92.236880,-20.369087,92.236880,20.369087,0,0,0,0,1,CLE,0.0,CLE,0.0,1.0,GR,0,0,0,0,0,0,0
10,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,9.270000000,1.0,10,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,LPR+ DZ,error,NaN,-96.260400,-13.327915,-96.260400,-13.327915,0,0,1,0,0,GR,0.0,CLE,0.0,1.0,GR,1,1,1,1,0,0,0
11,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,9.800000000,1.0,11,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,successful,eastside,DZ OUTLET PASS OFFBOARDS+,outletoffboards,NaN,-94.751580,-13.739403,-94.751580,-13.739403,0,0,1,0,0,GR,1.0,GR,0.0,0.0,GR,0,1,0,1,0,0,0
12,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,11.100000000,1.0,12,1,8cdcb61e-d733-bde6-a101-ef3140e48149,"L'Esperance, Joel",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,-52.001580,-34.954384,-52.001580,-34.954384,1,1,1,0,0,GR,1.0,GR,0.0,0.0,GR,0,1,0,1,0,0,0
13,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,12.370000000,1.0,13,1,8cdcb61e-d733-bde6-a101-ef3140e48149,"L'Esperance, Joel",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpout,successful,None,DUMP OUT+,ice,NaN,-34.398636,-27.410270,-34.398636,-27.410270,1,1,1,0,0,GR,1.0,GR,0.0,0.0,CLE,0,1,0,1,0,0,0
14,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,16.330000000,1.0,14,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,HI PRESS DUMP IN LPR+,hipresopdump,NaN,71.219010,39.983852,-71.219010,-39.983852,0,0,1,0,0,CLE,1.0,GR,0.0,0.0,CLE,1,2,1,1,0,0,1
15,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,18.170000000,1.0,15,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,DZONE D2D+,d2d,NaN,72.224900,38.977970,-72.224900,-38.977970,0,0,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,2,0,1,0,0,0
16,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,21.400000000,1.0,16,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,70.213135,12.413540,-70.213135,-12.413540,1,1,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,2,0,1,0,0,0
17,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,23.600000000,1.0,17,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westside,DZ OUTLET PASS+,outlet,NaN,61.160187,-24.804108,-61.160187,24.804108,1,1,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,2,0,1,0,0,0
18,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,24.870000000,1.0,18,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,10.866066,-24.804108,-10.866066,24.804108,1,1,0,1,0,CLE,1.0,CLE,0.0,0.0,CLE,0,2,0,1,1,0,0
19,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,25.570000000,1.0,19,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,puckprotection,failed,None,NZDEKE-,deke,NaN,14.889603,-29.330574,-14.889603,29.330574,1,1,0,1,0,CLE,0.0,CLE,1.0,0.0,GR,0,2,0,1,0,0,0
20,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,27.930000000,1.0,20,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,LPR+ NZ,error,NaN,-12.772163,-35.457330,-12.772163,-35.457330,1,1,0,1,0,GR,0.0,CLE,1.0,0.0,GR,1,3,0,1,0,0,0
21,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,28.130000000,1.0,21,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,failed,eastside,NZPASS north-,north,NaN,-11.263344,-36.326035,-11.263344,-36.326035,1,1,0,1,0,GR,0.0,GR,1.0,0.0,GR,0,3,0,1,0,0,0
22,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,28.870000000,1.0,22,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,failedpasslocation,failed,None,FAILED PASS TRAJECTORY LOCATION NZ,none,NaN,8.854301,-30.793678,8.854301,-30.793678,1,1,0,1,0,GR,0.0,GR,1.0,0.0,CLE,0,3,0,1,0,0,0
23,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,30.400000000,1.0,23,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,DUMP IN LPR+,opdump,NaN,47.580780,-33.948500,-47.580780,33.948500,1,1,1,0,0,CLE,0.0,GR,1.0,0.0,CLE,1,4,1,1,0,0,0
24,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,31.170000000,2.0,24,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westeast,DZONE D2D+,d2d,NaN,67.195480,-31.342346,-67.195480,31.342346,1,1,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,4,0,1,0,0,0
25,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,32.170000000,2.0,25,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,59.148422,28.416204,-59.148422,-28.416204,0,0,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,4,0,1,0,0,0
26,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,33.530000000,2.0,26,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,DZ OUTLET PASS+,outlet,NaN,37.019012,32.942677,-37.019012,-32.942677,0,0,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,4,0,1,0,0,0
27,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,34.270000000,2.0,27,1,90e5f527-993f-a1ac-44b5-9fb226fa6128,"Whelan, Alex",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,14.386658,30.930910,-14.386658,-30.930910,0,0,0,1,0,CLE,1.0,CLE,0.0,0.0,CLE,0,4,0,1,1,0,0
28,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,35.770000000,2.0,28,1,90e5f527-993f-a1ac-44b5-9fb226fa6128,"Whelan, Alex",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpin,successful,"rim, eastofdot",DUMP IN+,dump,NaN,5.333717,36.554718,-5.333717,-36.554718,1,0,0,1,0,CLE,0.0,CLE,1.0,0.0,GR,0,4,0,1,0,0,0
29,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,35.770000000,2.0,29,1,015f554a-21c0-99bc-0a31-a176810b40c6,"Shine, Dominik",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpinagainst,undetermined,None,DUMPIN AGAINST,none,NaN,6.339600,35.503105,6.339600,35.503105,1,1,0,1,0,GR,0.0,CLE,1.0,0.0,GR,0,4,0,1,0,0,0
30,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,39.330000000,4.0,30,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,NO PRESSURE LPR+,nofore,NaN,-93.745700,18.951777,-93.745700,18.951777,1,1,1,0,0,GR,0.0,GR,1.0,0.0,GR,0,4,0,1,0,0,0
31,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,41.500000000,4.0,31,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,controlledbreakout,undetermined,None,CONTROLLED BREAKOUT,none,NaN,-71.113340,-15.842621,-71.113340,-15.842621,0,0,1,0,0,GR,1.0,GR,0.0,0.0,GR,0,4,0,1,0,0,0
32,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,43.670000000,6.0,32,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,carry,successful,None,CONTROLLED EXIT FROM DZ,none,NaN,-24.339813,7.795616,-24.339813,7.795616,1,1,0,1,0,GR,1.0,GR,0.0,0.0,GR,0,4,0,1,1,0,0
33,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,43.870000000,6.0,33,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,failed,westside,NZPASS north-,north,NaN,-19.813340,13.830910,-19.813340,13.830910,1,1,0,1,0,GR,0.0,GR,1.0,0.0,GR,0,4,0,1,0,0,0
34,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,44.900000000,6.0,34,1,7a213ae8-292c-bc7f-83dd-7b14bdcadde1,"Berggren, Jonatan",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,reception,failed,None,MISS PASS,regular,NaN,5.333717,34.954437,5.333717,34.954437,1,1,0,1,0,GR,0.0,GR,1.0,0.0,GR,0,4,0,1,0,0,0
35,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,45.930000000,6.0,35,1,7a213ae8-292c-bc7f-83dd-7b14bdcadde1,"Berggren, Jonatan",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,OFF LPR NZ,none,NaN,16.398422,36.463260,16.398422,36.463260,1,1,0,1,0,GR,0.0,GR,1.0,0.0,GR,0,4,0,1,0,0,0
36,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,45.970000000,6.0,36,1,7a213ae8-292c-bc7f-83dd-7b14bdcadde1,"Berggren, Jonatan",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpin,successful,"rim, westofdot",DUMP IN+,dump,NaN,15.895485,36.554718,15.895485,36.554718,1,1,0,1,0,GR,0.0,GR,1.0,0.0,CLE,0,4,0,1,0,0,0
37,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,45.970000000,6.0,37,1,4447229a-e693-b7a3-6bbe-f464ae9917c4,"Pyyhtia, Mikael",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpinagainst,undetermined,None,DUMPIN AGAINST,none,NaN,17.907250,30.976633,-17.907250,-30.976633,1,1,0,1,0,CLE,0.0,GR,1.0,0.0,CLE,0,4,0,1,0,0,0
38,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,47.200000000,6.0,38,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,DUMP IN LPR+,opdump,NaN,47.077835,34.954437,-47.077835,-34.954437,1,0,1,0,0,CLE,0.0,CLE,1.0,0.0,CLE,0,4,0,1,0,0,0
39,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,48.470000000,6.0,39,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastwest,DZONE D2D+,d2d,NaN,61.160187,29.422087,-61.160187,-29.422087,1,0,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,4,0,1,0,0,0
40,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,49.030000000,6.0,40,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,75.242540,-15.842621,-75.242540,15.842621,1,1,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,4,0,1,0,0,0
41,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,50.230000000,6.0,41,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westside,DZONE D2D+,d2d,NaN,88.319016,-26.907326,-88.319016,26.907326,1,1,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,4,0,1,0,0,0
42,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,52.230000000,6.0,42,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,33.498430,-28.416153,-33.498430,28.416153,1,1,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,4,0,1,0,0,0
43,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,52.830000000,6.0,43,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,failed,westside,DZONE D2D-,d2d,NaN,35.007248,-25.901443,-35.007248,25.901443,1,1,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,4,0,1,0,0,0
44,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,53.500000000,6.0,44,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,failedpasslocation,failed,None,FAILED PASS TRAJECTORY LOCATION DZ,none,NaN,60.657240,-23.889679,-60.657240,23.889679,1,1,1,0,0,CLE,1.0,CLE,0.0,0.0,GR,0,4,0,1,0,0,0
45,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,54.030000000,6.0,45,1,cf9158fc-30e9-680c-b9e5-b65717e1e000,"Czarnik, Austin",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,None,OPPOSITION DUMP LPR,opdump,NaN,20.421951,-16.848503,20.421951,-16.848503,1,1,0,1,0,GR,1.0,CLE,0.0,0.0,GR,1,5,0,1,0,0,1
46,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,55.530000000,6.0,46,1,cf9158fc-30e9-680c-b9e5-b65717e1e000,"Czarnik, Austin",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,successful,westside,SOUTH CYCLE +,south,NaN,35.510193,10.813263,35.510193,10.813263,1,1,0,0,1,GR,0.0,GR,1.0,0.0,GR,0,5,0,1,0,0,0
47,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,57.230000000,6.0,47,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,20.924896,37.057660,20.924896,37.057660,1,1,0,1,0,GR,0.0,GR,0.0,1.0,GR,0,5,0,1,0,0,0
48,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,57.270000000,6.0,48,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpin,successful,"rim, westofdot",DUMP IN+,dump,NaN,22.433716,38.063540,22.433716,38.063540,1,1,0,1,0,GR,0.0,GR,1.0,0.0,CLE,0,5,0,1,0,0,0
49,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,57.270000000,6.0,49,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpinagainst,undetermined,None,DUMPIN AGAINST,none,NaN,36.013123,32.439730,-36.013123,-32.439730,1,1,1,0,0,CLE,0.0,GR,1.0,0.0,GR,0,5,0,1,0,0,0
50,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,60.670000000,6.0,50,1,65195a5e-8639-a163-d566-03adc8582060,"Tuomisto, Antti",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,None,DI LPR OZ,none,NaN,32.492540,-29.330574,32.492540,-29.330574,1,1,0,0,1,GR,1.0,CLE,0.0,0.0,GR,1,6,0,1,0,1,0
51,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,60.700000000,6.0,51,1,65195a5e-8639-a163-d566-03adc8582060,"Tuomisto, Antti",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,failed,eastside,NORTH CYCLE OFFBOARDS-,northoffboards,NaN,35.510193,-28.827637,35.510193,-28.827637,1,1,0,0,1,GR,0.0,GR,0.0,1.0,CLE,0,6,0,1,0,0,0
52,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,63.600000000,6.0,52,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,block,successful,None,BLOCK OPPOSITION PASS+,pass,NaN,84.798416,-4.274971,-84.798416,4.274971,1,0,1,0,0,CLE,0.0,GR,0.0,1.0,GR,0,6,0,1,0,0,0
53,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,63.600000000,6.0,53,1,65195a5e-8639-a163-d566-03adc8582060,"Tuomisto, Antti",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,failedpasslocation,failed,None,FAILED PASS TRAJECTORY LOCATION OZ,none,NaN,95.863130,-4.686459,95.863130,-4.686459,1,0,0,0,1,GR,1.0,CLE,0.0,0.0,CLE,0,6,0,1,0,0,0
54,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,66.070000000,6.0,54,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,DEF LPR DZ,none,NaN,88.821960,-24.895561,-88.821960,24.895561,0,0,1,0,0,CLE,0.0,GR,0.0,1.0,CLE,1,7,1,1,0,0,0
55,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,66.400000000,6.0,55,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westeast,DZONE D2D+,d2d,NaN,91.336655,-26.312927,-91.336655,26.312927,0,0,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,7,0,1,0,0,0
56,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,68.200000000,6.0,56,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,90.833725,18.860321,-90.833725,-18.860321,1,0,1,0,0,CLE,1.0,CLE,0.0,0.0,CLE,0,7,0,1,0,0,0

In [146]:
events["dz_start_possession"].value_counts()

dz_start_possession
1    1796959
0       3505
Name: count, dtype: int64

In [142]:
events["controlled_exit"].value_counts()

controlled_exit
0    1721483
1      78981
Name: count, dtype: int64

In [144]:
events["dz_turnover"].value_counts()

dz_turnover
0    1740548
1      59916
Name: count, dtype: int64

In [145]:
events["leave_dz_without_puck"].value_counts()

leave_dz_without_puck
0    1774927
1      25537
Name: count, dtype: int64

In [103]:
events["dzone"] = (events["x_adj"] < -25.0).astype(int)
events["nzone"] = ((events["x_adj"] >= -25.0) & (events["x_adj"] <= 25.0)).astype(int)
events["ozone"] = (events["x_adj"] > 25.0).astype(int)
events["poss_team"] = events["team"]

g = events.groupby(["game_id", "sequence_id"])

events["prev_dzone"] = g["dzone"].shift(1)
events["prev_team"] = g["poss_team"].shift(1)
events["prev_nzone"] = g["nzone"].shift(1)
events["prev_ozone"] = g["ozone"].shift(1)
events["next_team"] = g["poss_team"].shift(-1)

# Start: team gains possession in dzone AND maintains it for next event
events["dz_possession_start"] = (
    (events["dzone"] == 1) &
    (events["event_type"]=="lpr") &
    (events["poss_team"] != events["prev_team"]) &
    (events["poss_team"] == events["next_team"])  # Keep this!
).astype(int)

events["poss_id"] = events.groupby("game_id")["dzpossession_start"].cumsum()
events["

events["dz_exit"] = (
    #team exits the zone with possession
    ((((events["nzone"] == 1) | (events["ozone"] == 1)) & 
    (events["prev_dzone"]==1) &
    (events["poss_team"] == events["prev_team"]))
    #team gets the puck out of the zone, loses possession in doing so
    | (((events["nzone"] == 1) | (events["dzone"] == 1)) & (events["event_type"]=="lpr") & 
       (events["prev_dzone"] == 1) &
        (events["poss_team"] != events["prev_team"])))
).astype(int)

events["dz_turnover"] = (
    ((events["ozone"] == 1) & (events["event_type"] == "lpr") &
    (events["prev_dzone"] == 1) &
    (events["poss_team"] != events["prev_team"]))
).astype(int)

In [122]:
events["next_event"]=events["event_type"].shift(-1)

In [126]:
events["event_type"].value_counts()

event_type
pass                      402670
lpr                       338836
reception                 304903
carry                     110362
failedpasslocation         97366
faceoff                    84621
block                      66233
puckprotection             54827
shot                       53971
pressure                   53961
controlledentryagainst     38081
dumpout                    35152
dumpin                     34740
dumpinagainst              32182
whistle                    25397
check                      24992
penalty                    11547
goal                        5667
controlledbreakout          4956
assist                      4793
icing                       4052
penaltydrawn                3765
receptionprevention         2353
deflection                  2047
offside                     2003
solpr                        237
socarry                      237
soshot                       231
sogoal                        76
shootout                      70
teamwithozonright             50
penaltyshot                   40
pslpr                         19
pscarry                       19
sopuckprotection               7
socheck                        1
Name: count, dtype: int64

In [125]:
events[events["event_type"]=="puckprotection"]["next_event"].value_counts()

next_event
lpr                       33341
pass                      10366
check                      2495
carry                      2400
puckprotection             2059
pressure                   1416
whistle                     689
penalty                     446
dumpout                     409
penaltydrawn                310
dumpin                      231
block                       231
offside                     144
controlledentryagainst      135
dumpinagainst                50
shot                         48
controlledbreakout           20
reception                    19
failedpasslocation           14
assist                        4
Name: count, dtype: int64

In [106]:
events[events["event_type"]=="failedpasslocation"]["next_event"].value_counts()

next_event
lpr                       84124
block                      3738
whistle                    3563
pass                       2345
pressure                    840
offside                     417
dumpout                     371
carry                       343
penalty                     324
puckprotection              227
reception                   194
receptionprevention         181
penaltydrawn                176
check                       157
shot                        112
dumpin                       81
dumpinagainst                73
icing                        60
assist                       14
controlledbreakout           10
failedpasslocation            9
controlledentryagainst        6
goal                          1
Name: count, dtype: int64

In [107]:
events["potential_end"].value_counts()

potential_end
0    1635913
1     164551
Name: count, dtype: int64

In [108]:
events.head(60)

,game_id,period,period_time,game_stint,sl_event_id,sequence_id,player_id,player_name,team,team_id,opp_team,opp_team_id,event_type,outcome,flags,description,detail,sl_xg_all_shots,x,y,x_adj,y_adj,has_tracking_data,event_player_tracked,dzone,nzone,ozone,poss_team,dz_possession_start,dz_exit,dz_turnover,potential_end,cum_starts,next_event,cum_potential_ends,in_dz_possession
0,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,0,1,None,None,None,None,None,None,faceoff,None,None,Face-Off,nz,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,0,faceoff,0.0,0.0
1,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,1,1,8cdcb61e-d733-bde6-a101-ef3140e48149,"L'Esperance, Joel",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,faceoff,failed,"centerfodot, righthandedopponent",NZ FACE OFF-,none,NaN,-0.201431,-0.755550,-0.201431,-0.755550,1,1,0,1,0,GR,0,0,0,0,0,faceoff,0.0,0.0
2,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,2,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,faceoff,successful,"centerfodot, righthandedopponent",NZ REC FACE OFF+ENTRY,recoveredwithentry,NaN,-0.201431,-0.755550,0.201431,0.755550,1,1,0,1,0,CLE,0,0,0,0,0,lpr,0.0,0.0
3,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.070000000,1.0,3,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,None,F/OFF LPR+ NZ,faceoff,NaN,0.807243,1.257381,-0.807243,-1.257381,1,1,0,1,0,CLE,0,0,0,0,0,pass,0.0,0.0
4,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.130000000,1.0,4,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,NZPASS south+,south,NaN,0.304306,0.845894,-0.304306,-0.845894,1,1,0,1,0,CLE,0,0,0,0,0,reception,0.0,0.0
5,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,2.200000000,1.0,5,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,6.339600,20.917810,-6.339600,-20.917810,1,1,0,1,0,CLE,0,0,0,0,0,pass,0.0,0.0
6,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,2.470000000,1.0,6,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,NZPASS north+,north,NaN,6.339600,23.386793,-6.339600,-23.386793,1,1,0,1,0,CLE,0,0,0,0,0,reception,0.0,0.0
7,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,3.370000000,1.0,7,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,-23.839119,20.872547,23.839119,-20.872547,1,1,0,1,0,CLE,0,0,0,0,0,pass,0.0,0.0
8,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,4.430000000,1.0,8,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,failed,eastwest,NORTH CYCLE OFFBOARDS-,northoffboards,NaN,-43.451580,25.992952,43.451580,-25.992952,1,1,0,0,1,CLE,0,0,0,0,0,reception,0.0,0.0
9,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,7.130000000,1.0,9,1,0f052c34-6cd2-f4fd-a861-d9051a8e86e4,"Angle, Tyler",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,failed,None,MISS PASS,regular,NaN,-92.236880,-20.369087,92.236880,20.369087,0,0,0,0,1,CLE,0,0,0,0,0,lpr,0.0,0.0
10,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,9.270000000,1.0,10,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,LPR+ DZ,error,NaN,-96.260400,-13.327915,-96.260400,-13.327915,0,0,1,0,0,GR,1,0,0,0,1,pass,0.0,1.0
11,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,9.800000000,1.0,11,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,successful,eastside,DZ OUTLET PASS OFFBOARDS+,outletoffboards,NaN,-94.751580,-13.739403,-94.751580,-13.739403,0,0,1,0,0,GR,0,0,0,0,1,reception,0.0,1.0
12,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,11.100000000,1.0,12,1,8cdcb61e-d733-bde6-a101-ef3140e48149,"L'Esperance, Joel",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,-52.001580,-34.954384,-52.001580,-34.954384,1,1,1,0,0,GR,0,0,0,0,1,dumpout,0.0,1.0
13,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,12.370000000,1.0,13,1,8cdcb61e-d733-bde6-a101-ef3140e48149,"L'Esperance, Joel",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpout,successful,None,DUMP OUT+,ice,NaN,-34.398636,-27.410270,-34.398636,-27.410270,1,1,1,0,0,GR,0,0,0,0,1,lpr,0.0,1.0
14,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,16.330000000,1.0,14,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,HI PRESS DUMP IN LPR+,hipresopdump,NaN,71.219010,39.983852,-71.219010,-39.983852,0,0,1,0,0,CLE,1,1,0,1,2,pass,0.0,2.0
15,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,18.170000000,1.0,15,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,DZONE D2D+,d2d,NaN,72.224900,38.977970,-72.224900,-38.977970,0,0,1,0,0,CLE,0,0,0,0,2,reception,1.0,1.0
16,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,21.400000000,1.0,16,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,70.213135,12.413540,-70.213135,-12.413540,1,1,1,0,0,CLE,0,0,0,0,2,pass,1.0,1.0
17,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,23.600000000,1.0,17,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westside,DZ OUTLET PASS+,outlet,NaN,61.160187,-24.804108,-61.160187,24.804108,1,1,1,0,0,CLE,0,0,0,0,2,reception,1.0,1.0
18,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,24.870000000,1.0,18,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,10.866066,-24.804108,-10.866066,24.804108,1,1,0,1,0,CLE,0,1,0,1,2,puckprotection,1.0,1.0
19,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,25.570000000,1.0,19,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,puckprotection,failed,None,NZDEKE-,deke,NaN,14.889603,-29.330574,-14.889603,29.330574,1,1,0,1,0,CLE,0,0,0,0,2,lpr,2.0,0.0
20,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,27.930000000,1.0,20,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,LPR+ NZ,error,NaN,-12.772163,-35.457330,-12.772163,-35.457330,1,1,0,1,0,GR,0,0,0,0,2,pass,2.0,0.0
21,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,28.130000000,1.0,21,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,failed,eastside,NZPASS north-,north,NaN,-11.263344,-36.326035,-11.263344,-36.326035,1,1,0,1,0,GR,0,0,0,0,2,failedpasslocation,2.0,0.0
22,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,28.870000000,1.0,22,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,failedpasslocation,failed,None,FAILED PASS TRAJECTORY LOCATION NZ,none,NaN,8.854301,-30.793678,8.854301,-30.793678,1,1,0,1,0,GR,0,0,0,0,2,lpr,2.0,0.0
23,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,30.400000000,1.0,23,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,DUMP IN LPR+,opdump,NaN,47.580780,-33.948500,-47.580780,33.948500,1,1,1,0,0,CLE,1,0,0,0,3,pass,2.0,1.0
24,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,31.170000000,2.0,24,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westeast,DZONE D2D+,d2d,NaN,67.195480,-31.342346,-67.195480,31.342346,1,1,1,0,0,CLE,0,0,0,0,3,reception,2.0,1.0
25,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,32.170000000,2.0,25,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,59.148422,28.416204,-59.148422,-28.416204,0,0,1,0,0,CLE,0,0,0,0,3,pass,2.0,1.0
26,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,33.530000000,2.0,26,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,DZ OUTLET PASS+,outlet,NaN,37.019012,32.942677,-37.019012,-32.942677,0,0,1,0,0,CLE,0,0,0,0,3,reception,2.0,1.0
27,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,34.270000000,2.0,27,1,90e5f527-993f-a1ac-44b5-9fb226fa6128,"Whelan, Alex",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,14.386658,30.930910,-14.386658,-30.930910,0,0,0,1,0,CLE,0,1,0,1,3,dumpin,2.0,1.0
28,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,35.770000000,2.0,28,1,90e5f527-993f-a1ac-44b5-9fb226fa6128,"Whelan, Alex",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpin,successful,"rim, eastofdot",DUMP IN+,dump,NaN,5.333717,36.554718,-5.333717,-36.554718,1,0,0,1,0,CLE,0,0,0,0,3,dumpinagainst,3.0,0.0
29,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,35.770000000,2.0,29,1,015f554a-21c0-99bc-0a31-a176810b40c6,"Shine, Dominik",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpinagainst,undetermined,None,DUMPIN AGAINST,none,NaN,6.339600,35.503105,6.339600,35.503105,1,1,0,1,0,GR,0,0,0,0,3,lpr,3.0,0.0
30,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,39.330000000,4.0,30,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,NO PRESSURE LPR+,nofore,NaN,-93.745700,18.951777,-93.745700,18.951777,1,1,1,0,0,GR,1,0,0,0,4,controlledbreakout,3.0,1.0
31,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,41.500000000,4.0,31,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,controlledbreakout,undetermined,None,CONTROLLED BREAKOUT,none,NaN,-71.113340,-15.842621,-71.113340,-15.842621,0,0,1,0,0,GR,0,0,0,0,4,carry,3.0,1.0
32,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,43.670000000,6.0,32,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,carry,successful,None,CONTROLLED EXIT FROM DZ,none,NaN,-24.339813,7.795616,-24.339813,7.795616,1,1,0,1,0,GR,0,1,0,1,4,pass,3.0,1.0
33,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,43.870000000,6.0,33,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,failed,westside,NZPASS north-,north,NaN,-19.813340,13.830910,-19.813340,13.830910,1,1,0,1,0,GR,0,0,0,0,4,reception,4.0,0.0
34,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,44.900000000,6.0,34,1,7a213ae8-292c-bc7f-83dd-7b14bdcadde1,"Berggren, Jonatan",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,reception,failed,None,MISS PASS,regular,NaN,5.333717,34.954437,5.333717,34.954437,1,1,0,1,0,GR,0,0,0,0,4,lpr,4.0,0.0
35,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,45.930000000,6.0,35,1,7a213ae8-292c-bc7f-83dd-7b14bdcadde1,"Berggren, Jonatan",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,OFF LPR NZ,none,NaN,16.398422,36.463260,16.398422,36.463260,1,1,0,1,0,GR,0,0,0,0,4,dumpin,4.0,0.0
36,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,45.970000000,6.0,36,1,7a213ae8-292c-bc7f-83dd-7b14bdcadde1,"Berggren, Jonatan",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpin,successful,"rim, westofdot",DUMP IN+,dump,NaN,15.895485,36.554718,15.895485,36.554718,1,1,0,1,0,GR,0,0,0,0,4,dumpinagainst,4.0,0.0
37,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,45.970000000,6.0,37,1,4447229a-e693-b7a3-6bbe-f464ae9917c4,"Pyyhtia, Mikael",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpinagainst,undetermined,None,DUMPIN AGAINST,none,NaN,17.907250,30.976633,-17.907250,-30.976633,1,1,0,1,0,CLE,0,0,0,0,4,lpr,4.0,0.0
38,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,47.200000000,6.0,38,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,DUMP IN LPR+,opdump,NaN,47.077835,34.954437,-47.077835,-34.954437,1,0,1,0,0,CLE,1,0,0,0,5,pass,4.0,1.0
39,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,48.470000000,6.0,39,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastwest,DZONE D2D+,d2d,NaN,61.160187,29.422087,-61.160187,-29.422087,1,0,1,0,0,CLE,0,0,0,0,5,reception,4.0,1.0
40,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,49.030000000,6.0,40,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,75.242540,-15.842621,-75.242540,15.842621,1,1,1,0,0,CLE,0,0,0,0,5,pass,4.0,1.0
41,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,50.230000000,6.0,41,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westside,DZONE D2D+,d2d,NaN,88.319016,-26.907326,-88.319016,26.907326,1,1,1,0,0,CLE,0,0,0,0,5,reception,4.0,1.0
42,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,52.230000000,6.0,42,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,33.498430,-28.416153,-33.498430,28.416153,1,1,1,0,0,CLE,0,0,0,0,5,pass,4.0,1.0
43,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,52.830000000,6.0,43,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,failed,westside,DZONE D2D-,d2d,NaN,35.007248,-25.901443,-35.007248,25.901443,1,1,1,0,0,CLE,0,0,0,0,5,failedpasslocation,4.0,1.0
44,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,53.500000000,6.0,44,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,failedpasslocation,failed,None,FAILED PASS TRAJECTORY LOCATION DZ,none,NaN,60.657240,-23.889679,-60.657240,23.889679,1,1,1,0,0,CLE,0,0,0,0,5,lpr,4.0,1.0
45,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,54.030000000,6.0,45,1,cf9158fc-30e9-680c-b9e5-b65717e1e000,"Czarnik, Austin",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,None,OPPOSITION DUMP LPR,opdump,NaN,20.421951,-16.848503,20.421951,-16.848503,1,1,0,1,0,GR,0,1,0,1,5,pass,4.0,1.0
46,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,55.530000000,6.0,46,1,cf9158fc-30e9-680c-b9e5-b65717e1e000,"Czarnik, Austin",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,successful,westside,SOUTH CYCLE +,south,NaN,35.510193,10.813263,35.510193,10.813263,1,1,0,0,1,GR,0,0,0,0,5,reception,5.0,0.0
47,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,57.230000000,6.0,47,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,20.924896,37.057660,20.924896,37.057660,1,1,0,1,0,GR,0,0,0,0,5,dumpin,5.0,0.0
48,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,57.270000000,6.0,48,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpin,successful,"rim, westofdot",DUMP IN+,dump,NaN,22.433716,38.063540,22.433716,38.063540,1,1,0,1,0,GR,0,0,0,0,5,dumpinagainst,5.0,0.0
49,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,57.270000000,6.0,49,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpinagainst,undetermined,None,DUMPIN AGAINST,none,NaN,36.013123,32.439730,-36.013123,-32.439730,1,1,1,0,0,CLE,0,0,0,0,5,lpr,5.0,0.0
50,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,60.670000000,6.0,50,1,65195a5e-8639-a163-d566-03adc8582060,"Tuomisto, Antti",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,None,DI LPR OZ,none,NaN,32.492540,-29.330574,32.492540,-29.330574,1,1,0,0,1,GR,0,0,0,1,5,pass,5.0,0.0
51,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,60.700000000,6.0,51,1,65195a5e-8639-a163-d566-03adc8582060,"Tuomisto, Antti",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,failed,eastside,NORTH CYCLE OFFBOARDS-,northoffboards,NaN,35.510193,-28.827637,35.510193,-28.827637,1,1,0,0,1,GR,0,0,0,0,5,block,6.0,-1.0
52,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,63.600000000,6.0,52,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,block,successful,None,BLOCK OPPOSITION PASS+,pass,NaN,84.798416,-4.274971,-84.798416,4.274971,1,0,1,0,0,CLE,0,0,0,0,5,failedpasslocation,6.0,-1.0
53,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,63.600000000,6.0,53,1,65195a5e-8639-a163-d566-03adc8582060,"Tuomisto, Antti",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,failedpasslocation,failed,None,FAILED PASS TRAJECTORY LOCATION OZ,none,NaN,95.863130,-4.686459,95.863130,-4.686459,1,0,0,0,1,GR,0,0,0,0,5,lpr,6.0,-1.0
54,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,66.070000000,6.0,54,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,DEF LPR DZ,none,NaN,88.821960,-24.895561,-88.821960,24.895561,0,0,1,0,0,CLE,1,0,0,0,6,pass,6.0,0.0
55,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,66.400000000,6.0,55,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westeast,DZONE D2D+,d2d,NaN,91.336655,-26.312927,-91.336655,26.312927,0,0,1,0,0,CLE,0,0,0,0,6,reception,6.0,0.0
56,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,68.200000000,6.0,56,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,90.833725,18.860321,-90.833725,-18.860321,1,0,1,0,0,CLE,0,0,0,0,6,dumpout,6.0,0.0
57,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,68.730000000,6.0,57,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpout,failed,None,OFF GLASS DUMP OUT-,boards,NaN,90.833725,24.392675,-90.833725,-24.392675,1,0,1,0,0,CLE,0,0,0,0,6,lpr,6.0,0.0
58,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,69.770000000,6.0,58,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,LPR+ OZ,error,NaN,36.013123,34.451496,36.013123,34.451496,1,1,0,0,1,GR,0,0,0,1,6,pass,6.0,0.0

In [114]:
events["dz_possession_start"].value_counts()

dz_possession_start
0    1674981
1     125483
Name: count, dtype: int64

In [115]:
events["dz_exit"].value_counts()

dz_exit
0    1800458
1          6
Name: count, dtype: int64

In [116]:
events["dz_turnover"].value_counts()

dz_turnover
0    1800464
Name: count, dtype: int64

In [112]:
events[events["dz_turnover"]==1]["event_type"].value_counts()

Series([], Name: count, dtype: int64)

In [69]:
events[(events["event_type"]=="penalty")]

,game_id,period,period_time,game_stint,sl_event_id,sequence_id,player_id,player_name,team,team_id,opp_team,opp_team_id,event_type,outcome,flags,description,detail,sl_xg_all_shots,x,y,x_adj,y_adj,has_tracking_data,event_player_tracked,dzone,nzone,ozone,poss_team,dz_possession_start,dz_exit,dz_turnover,potential_end,cum_starts
217,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,257.870000000,34.0,217,3,663df049-a045-0561-16e3-1db633a0723e,"Aston-Reese, Zachary",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,penalty,successful,None,TRIPPING PENALTY OZ,tripping,NaN,61.660324,-18.358490,61.660324,-18.358490,1,1,0,0,1,GR,0,0,1,1,5
230,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,273.030000000,35.0,230,3,None,None,None,None,None,None,penalty,None,None,Penalty Start,start,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,6
295,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,332.030000000,43.0,295,4,None,None,None,None,None,None,penalty,None,None,Penalty End,end,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,4
534,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,576.700000000,62.0,534,9,e9ef1506-4a97-1586-e7b4-a1dfbec02e4e,"Fix-Wolansky, Trey",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,penalty,successful,None,ROUGHING PENALTY NZ,roughing,NaN,18.910332,37.970920,-18.910332,-37.970920,1,0,0,1,0,CLE,0,0,0,0,5
535,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,577.000000000,62.0,535,9,4772aa22-208f-44a0-8e47-0029da368b48,"Kasper, Marco",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,penalty,successful,None,ROUGHING PENALTY NZ,roughing,NaN,19.916214,38.473860,19.916214,38.473860,1,1,0,1,0,GR,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1799873,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,648.030000000,344.0,3009,41,None,None,None,None,None,None,penalty,None,None,Penalty Start,start,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,None,0,0,0,0,4
1799974,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,768.030000000,358.0,3110,43,None,None,None,None,None,None,penalty,None,None,Penalty End,end,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,None,0,0,0,0,2
1800019,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,821.830000000,361.0,3155,44,b90aa353-979c-854a-6f54-5a714d009b15,"Hall, Curtis",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,penalty,successful,None,SLASHING PENALTY NZ,slashing,NaN,-22.327347,9.808823,-22.327347,9.808823,1,1,0,1,0,GR,0,0,0,0,1
1800024,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,824.030000000,361.0,3160,44,None,None,None,None,None,None,penalty,None,None,Penalty Start,start,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,2
1800155,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,944.030000000,370.0,3291,45,None,None,None,None,None,None,penalty,None,None,Penalty End,end,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,2

In [119]:
events.head(60)

,game_id,period,period_time,game_stint,sl_event_id,sequence_id,player_id,player_name,team,team_id,opp_team,opp_team_id,event_type,outcome,flags,description,detail,sl_xg_all_shots,x,y,x_adj,y_adj,has_tracking_data,event_player_tracked,dzone,nzone,ozone,poss_team,dz_possession_start,dz_exit,dz_turnover,potential_end,cum_starts,next_event,cum_potential_ends,in_dz_possession,potential_exit,potential_turnover
0,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,0,1,None,None,None,None,None,None,faceoff,None,None,Face-Off,nz,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,0,faceoff,0.0,0.0,0,0
1,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,1,1,8cdcb61e-d733-bde6-a101-ef3140e48149,"L'Esperance, Joel",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,faceoff,failed,"centerfodot, righthandedopponent",NZ FACE OFF-,none,NaN,-0.201431,-0.755550,-0.201431,-0.755550,1,1,0,1,0,GR,0,0,0,0,0,faceoff,0.0,0.0,0,0
2,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,2,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,faceoff,successful,"centerfodot, righthandedopponent",NZ REC FACE OFF+ENTRY,recoveredwithentry,NaN,-0.201431,-0.755550,0.201431,0.755550,1,1,0,1,0,CLE,0,0,0,0,0,lpr,0.0,0.0,0,0
3,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.070000000,1.0,3,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,None,F/OFF LPR+ NZ,faceoff,NaN,0.807243,1.257381,-0.807243,-1.257381,1,1,0,1,0,CLE,0,0,0,0,0,pass,0.0,0.0,0,0
4,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.130000000,1.0,4,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,NZPASS south+,south,NaN,0.304306,0.845894,-0.304306,-0.845894,1,1,0,1,0,CLE,0,0,0,0,0,reception,0.0,0.0,0,0
5,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,2.200000000,1.0,5,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,6.339600,20.917810,-6.339600,-20.917810,1,1,0,1,0,CLE,0,0,0,0,0,pass,0.0,0.0,0,0
6,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,2.470000000,1.0,6,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,NZPASS north+,north,NaN,6.339600,23.386793,-6.339600,-23.386793,1,1,0,1,0,CLE,0,0,0,0,0,reception,0.0,0.0,0,0
7,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,3.370000000,1.0,7,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,-23.839119,20.872547,23.839119,-20.872547,1,1,0,1,0,CLE,0,0,0,0,0,pass,0.0,0.0,0,0
8,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,4.430000000,1.0,8,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,failed,eastwest,NORTH CYCLE OFFBOARDS-,northoffboards,NaN,-43.451580,25.992952,43.451580,-25.992952,1,1,0,0,1,CLE,0,0,0,0,0,reception,0.0,0.0,0,0
9,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,7.130000000,1.0,9,1,0f052c34-6cd2-f4fd-a861-d9051a8e86e4,"Angle, Tyler",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,failed,None,MISS PASS,regular,NaN,-92.236880,-20.369087,92.236880,20.369087,0,0,0,0,1,CLE,0,0,0,0,0,lpr,0.0,0.0,0,0
10,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,9.270000000,1.0,10,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,LPR+ DZ,error,NaN,-96.260400,-13.327915,-96.260400,-13.327915,0,0,1,0,0,GR,1,0,0,0,1,pass,0.0,1.0,0,0
11,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,9.800000000,1.0,11,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,successful,eastside,DZ OUTLET PASS OFFBOARDS+,outletoffboards,NaN,-94.751580,-13.739403,-94.751580,-13.739403,0,0,1,0,0,GR,0,0,0,0,1,reception,0.0,1.0,0,0
12,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,11.100000000,1.0,12,1,8cdcb61e-d733-bde6-a101-ef3140e48149,"L'Esperance, Joel",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,-52.001580,-34.954384,-52.001580,-34.954384,1,1,1,0,0,GR,0,0,0,0,1,dumpout,0.0,1.0,0,0
13,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,12.370000000,1.0,13,1,8cdcb61e-d733-bde6-a101-ef3140e48149,"L'Esperance, Joel",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpout,successful,None,DUMP OUT+,ice,NaN,-34.398636,-27.410270,-34.398636,-27.410270,1,1,1,0,0,GR,0,0,0,0,1,lpr,0.0,1.0,0,0
14,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,16.330000000,1.0,14,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,HI PRESS DUMP IN LPR+,hipresopdump,NaN,71.219010,39.983852,-71.219010,-39.983852,0,0,1,0,0,CLE,1,1,0,1,2,pass,0.0,2.0,1,0
15,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,18.170000000,1.0,15,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,DZONE D2D+,d2d,NaN,72.224900,38.977970,-72.224900,-38.977970,0,0,1,0,0,CLE,0,0,0,0,2,reception,1.0,1.0,0,0
16,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,21.400000000,1.0,16,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,70.213135,12.413540,-70.213135,-12.413540,1,1,1,0,0,CLE,0,0,0,0,2,pass,1.0,1.0,0,0
17,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,23.600000000,1.0,17,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westside,DZ OUTLET PASS+,outlet,NaN,61.160187,-24.804108,-61.160187,24.804108,1,1,1,0,0,CLE,0,0,0,0,2,reception,1.0,1.0,0,0
18,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,24.870000000,1.0,18,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,10.866066,-24.804108,-10.866066,24.804108,1,1,0,1,0,CLE,0,1,0,1,2,puckprotection,1.0,1.0,1,0
19,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,25.570000000,1.0,19,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,puckprotection,failed,None,NZDEKE-,deke,NaN,14.889603,-29.330574,-14.889603,29.330574,1,1,0,1,0,CLE,0,0,0,0,2,lpr,2.0,0.0,0,0
20,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,27.930000000,1.0,20,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,LPR+ NZ,error,NaN,-12.772163,-35.457330,-12.772163,-35.457330,1,1,0,1,0,GR,0,0,0,0,2,pass,2.0,0.0,0,0
21,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,28.130000000,1.0,21,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,failed,eastside,NZPASS north-,north,NaN,-11.263344,-36.326035,-11.263344,-36.326035,1,1,0,1,0,GR,0,0,0,0,2,failedpasslocation,2.0,0.0,0,0
22,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,28.870000000,1.0,22,1,8682f8c1-304a-51d9-6663-158ca58fa6c9,"Didier, Josiah",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,failedpasslocation,failed,None,FAILED PASS TRAJECTORY LOCATION NZ,none,NaN,8.854301,-30.793678,8.854301,-30.793678,1,1,0,1,0,GR,0,0,0,0,2,lpr,2.0,0.0,0,0
23,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,30.400000000,1.0,23,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,DUMP IN LPR+,opdump,NaN,47.580780,-33.948500,-47.580780,33.948500,1,1,1,0,0,CLE,1,0,0,0,3,pass,2.0,1.0,0,0
24,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,31.170000000,2.0,24,1,cb8a6b8b-c5a6-4bfe-10b7-15c784b83a7d,"Bjork, Marcus",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westeast,DZONE D2D+,d2d,NaN,67.195480,-31.342346,-67.195480,31.342346,1,1,1,0,0,CLE,0,0,0,0,3,reception,2.0,1.0,0,0
25,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,32.170000000,2.0,25,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,59.148422,28.416204,-59.148422,-28.416204,0,0,1,0,0,CLE,0,0,0,0,3,pass,2.0,1.0,0,0
26,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,33.530000000,2.0,26,1,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,DZ OUTLET PASS+,outlet,NaN,37.019012,32.942677,-37.019012,-32.942677,0,0,1,0,0,CLE,0,0,0,0,3,reception,2.0,1.0,0,0
27,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,34.270000000,2.0,27,1,90e5f527-993f-a1ac-44b5-9fb226fa6128,"Whelan, Alex",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,14.386658,30.930910,-14.386658,-30.930910,0,0,0,1,0,CLE,0,1,0,1,3,dumpin,2.0,1.0,1,0
28,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,35.770000000,2.0,28,1,90e5f527-993f-a1ac-44b5-9fb226fa6128,"Whelan, Alex",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpin,successful,"rim, eastofdot",DUMP IN+,dump,NaN,5.333717,36.554718,-5.333717,-36.554718,1,0,0,1,0,CLE,0,0,0,0,3,dumpinagainst,3.0,0.0,0,0
29,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,35.770000000,2.0,29,1,015f554a-21c0-99bc-0a31-a176810b40c6,"Shine, Dominik",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpinagainst,undetermined,None,DUMPIN AGAINST,none,NaN,6.339600,35.503105,6.339600,35.503105,1,1,0,1,0,GR,0,0,0,0,3,lpr,3.0,0.0,0,0
30,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,39.330000000,4.0,30,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,NO PRESSURE LPR+,nofore,NaN,-93.745700,18.951777,-93.745700,18.951777,1,1,1,0,0,GR,1,0,0,0,4,controlledbreakout,3.0,1.0,0,0
31,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,41.500000000,4.0,31,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,controlledbreakout,undetermined,None,CONTROLLED BREAKOUT,none,NaN,-71.113340,-15.842621,-71.113340,-15.842621,0,0,1,0,0,GR,0,0,0,0,4,carry,3.0,1.0,0,0
32,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,43.670000000,6.0,32,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,carry,successful,None,CONTROLLED EXIT FROM DZ,none,NaN,-24.339813,7.795616,-24.339813,7.795616,1,1,0,1,0,GR,0,1,0,1,4,pass,3.0,1.0,1,0
33,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,43.870000000,6.0,33,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,failed,westside,NZPASS north-,north,NaN,-19.813340,13.830910,-19.813340,13.830910,1,1,0,1,0,GR,0,0,0,0,4,reception,4.0,0.0,0,0
34,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,44.900000000,6.0,34,1,7a213ae8-292c-bc7f-83dd-7b14bdcadde1,"Berggren, Jonatan",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,reception,failed,None,MISS PASS,regular,NaN,5.333717,34.954437,5.333717,34.954437,1,1,0,1,0,GR,0,0,0,0,4,lpr,4.0,0.0,0,0
35,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,45.930000000,6.0,35,1,7a213ae8-292c-bc7f-83dd-7b14bdcadde1,"Berggren, Jonatan",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,OFF LPR NZ,none,NaN,16.398422,36.463260,16.398422,36.463260,1,1,0,1,0,GR,0,0,0,0,4,dumpin,4.0,0.0,0,0
36,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,45.970000000,6.0,36,1,7a213ae8-292c-bc7f-83dd-7b14bdcadde1,"Berggren, Jonatan",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpin,successful,"rim, westofdot",DUMP IN+,dump,NaN,15.895485,36.554718,15.895485,36.554718,1,1,0,1,0,GR,0,0,0,0,4,dumpinagainst,4.0,0.0,0,0
37,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,45.970000000,6.0,37,1,4447229a-e693-b7a3-6bbe-f464ae9917c4,"Pyyhtia, Mikael",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpinagainst,undetermined,None,DUMPIN AGAINST,none,NaN,17.907250,30.976633,-17.907250,-30.976633,1,1,0,1,0,CLE,0,0,0,0,4,lpr,4.0,0.0,0,0
38,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,47.200000000,6.0,38,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,DUMP IN LPR+,opdump,NaN,47.077835,34.954437,-47.077835,-34.954437,1,0,1,0,0,CLE,1,0,0,0,5,pass,4.0,1.0,0,0
39,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,48.470000000,6.0,39,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastwest,DZONE D2D+,d2d,NaN,61.160187,29.422087,-61.160187,-29.422087,1,0,1,0,0,CLE,0,0,0,0,5,reception,4.0,1.0,0,0
40,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,49.030000000,6.0,40,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,75.242540,-15.842621,-75.242540,15.842621,1,1,1,0,0,CLE,0,0,0,0,5,pass,4.0,1.0,0,0
41,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,50.230000000,6.0,41,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westside,DZONE D2D+,d2d,NaN,88.319016,-26.907326,-88.319016,26.907326,1,1,1,0,0,CLE,0,0,0,0,5,reception,4.0,1.0,0,0
42,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,52.230000000,6.0,42,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,33.498430,-28.416153,-33.498430,28.416153,1,1,1,0,0,CLE,0,0,0,0,5,pass,4.0,1.0,0,0
43,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,52.830000000,6.0,43,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,failed,westside,DZONE D2D-,d2d,NaN,35.007248,-25.901443,-35.007248,25.901443,1,1,1,0,0,CLE,0,0,0,0,5,failedpasslocation,4.0,1.0,0,0
44,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,53.500000000,6.0,44,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,failedpasslocation,failed,None,FAILED PASS TRAJECTORY LOCATION DZ,none,NaN,60.657240,-23.889679,-60.657240,23.889679,1,1,1,0,0,CLE,0,0,0,0,5,lpr,4.0,1.0,0,0
45,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,54.030000000,6.0,45,1,cf9158fc-30e9-680c-b9e5-b65717e1e000,"Czarnik, Austin",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,None,OPPOSITION DUMP LPR,opdump,NaN,20.421951,-16.848503,20.421951,-16.848503,1,1,0,1,0,GR,0,1,0,1,5,pass,4.0,1.0,1,0
46,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,55.530000000,6.0,46,1,cf9158fc-30e9-680c-b9e5-b65717e1e000,"Czarnik, Austin",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,successful,westside,SOUTH CYCLE +,south,NaN,35.510193,10.813263,35.510193,10.813263,1,1,0,0,1,GR,0,0,0,0,5,reception,5.0,0.0,0,0
47,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,57.230000000,6.0,47,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,reception,successful,None,N-ZONE PASS RECEPTION,regular,NaN,20.924896,37.057660,20.924896,37.057660,1,1,0,1,0,GR,0,0,0,0,5,dumpin,5.0,0.0,0,0
48,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,57.270000000,6.0,48,1,a434fff2-8e1b-5bc6-1759-b545496778b5,"Edvinsson, Simon",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,dumpin,successful,"rim, westofdot",DUMP IN+,dump,NaN,22.433716,38.063540,22.433716,38.063540,1,1,0,1,0,GR,0,0,0,0,5,dumpinagainst,5.0,0.0,0,0
49,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,57.270000000,6.0,49,1,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpinagainst,undetermined,None,DUMPIN AGAINST,none,NaN,36.013123,32.439730,-36.013123,-32.439730,1,1,1,0,0,CLE,0,0,0,0,5,lpr,5.0,0.0,0,0
50,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,60.670000000,6.0,50,1,65195a5e-8639-a163-d566-03adc8582060,"Tuomisto, Antti",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,None,DI LPR OZ,none,NaN,32.492540,-29.330574,32.492540,-29.330574,1,1,0,0,1,GR,0,0,0,1,5,pass,5.0,0.0,0,1
51,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,60.700000000,6.0,51,1,65195a5e-8639-a163-d566-03adc8582060,"Tuomisto, Antti",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,pass,failed,eastside,NORTH CYCLE OFFBOARDS-,northoffboards,NaN,35.510193,-28.827637,35.510193,-28.827637,1,1,0,0,1,GR,0,0,0,0,5,block,6.0,-1.0,0,0
52,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,63.600000000,6.0,52,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,block,successful,None,BLOCK OPPOSITION PASS+,pass,NaN,84.798416,-4.274971,-84.798416,4.274971,1,0,1,0,0,CLE,0,0,0,0,5,failedpasslocation,6.0,-1.0,0,0
53,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,63.600000000,6.0,53,1,65195a5e-8639-a163-d566-03adc8582060,"Tuomisto, Antti",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,failedpasslocation,failed,None,FAILED PASS TRAJECTORY LOCATION OZ,none,NaN,95.863130,-4.686459,95.863130,-4.686459,1,0,0,0,1,GR,0,0,0,0,5,lpr,6.0,-1.0,0,0
54,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,66.070000000,6.0,54,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,DEF LPR DZ,none,NaN,88.821960,-24.895561,-88.821960,24.895561,0,0,1,0,0,CLE,1,0,0,0,6,pass,6.0,0.0,0,0
55,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,66.400000000,6.0,55,1,efbd8365-7b4a-13f4-6a00-d77d11d64910,"Christiansen, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,westeast,DZONE D2D+,d2d,NaN,91.336655,-26.312927,-91.336655,26.312927,0,0,1,0,0,CLE,0,0,0,0,6,reception,6.0,0.0,0,0
56,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,68.200000000,6.0,56,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,reception,successful,None,D-ZONE PASS RECEPTION,regular,NaN,90.833725,18.860321,-90.833725,-18.860321,1,0,1,0,0,CLE,0,0,0,0,6,dumpout,6.0,0.0,0,0
57,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,68.730000000,6.0,57,1,a5a0b510-df00-f72a-f892-86dc36da148c,"Clayton, Cole",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,dumpout,failed,None,OFF GLASS DUMP OUT-,boards,NaN,90.833725,24.392675,-90.833725,-24.392675,1,0,1,0,0,CLE,0,0,0,0,6,lpr,6.0,0.0,0,0

In [49]:
events[events["dz_turnover"]==1]["event_type"].shift(1).value_counts()

event_type
lpr                    53121
shot                   39496
pass                   27953
puckprotection         18692
block                  18486
faceoff                10095
reception               9898
check                   5655
failedpasslocation      3624
carry                   3232
deflection              1971
penaltydrawn            1193
penalty                  902
receptionprevention      653
assist                   422
pressure                 182
dumpin                    79
offside                   77
goal                       3
sopuckprotection           1
Name: count, dtype: int64

In [26]:
events[events["event_type"]=="goal"]

,game_id,period,period_time,game_stint,sl_event_id,sequence_id,player_id,player_name,team,team_id,opp_team,opp_team_id,event_type,outcome,flags,description,detail,sl_xg_all_shots,x,y,x_adj,y_adj,has_tracking_data,event_player_tracked,dzone,nzone,ozone,poss_team,dz_possession_start,dz_exit,dz_turnover,potential_end,cum_starts
293,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,331.500000000,43.0,293,4,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,goal,successful,None,GOAL,none,NaN,-69.603810,-21.876472,69.603810,21.876472,1,1,0,0,1,CLE,0,0,0,0,4
294,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,332.030000000,43.0,294,4,None,None,None,None,None,None,goal,None,None,Goal,none,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,4
431,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,463.400000000,56.0,431,7,2f0d296c-e9df-b8b7-f0e0-a135b8802329,"Soderblom, Elmer",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,goal,successful,None,GOAL,none,NaN,88.822660,4.779411,88.822660,4.779411,0,0,0,0,1,GR,0,0,0,0,2
432,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,464.030000000,56.0,432,7,None,None,None,None,None,None,goal,None,None,Goal,none,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,2
1384,00b0366a-95c6-5250-2dae-e3dd5c4198bc,2,195.530000000,167.0,1384,19,e9ef1506-4a97-1586-e7b4-a1dfbec02e4e,"Fix-Wolansky, Trey",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,goal,successful,None,GOAL,none,NaN,85.800280,4.075298,85.800280,4.075298,1,0,0,0,1,CLE,0,0,0,0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1798554,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,2,511.030000000,207.0,1688,26,None,None,None,None,None,None,goal,None,None,Goal,none,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,19
1800228,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,1000.270000000,374.0,3364,47,2f0d296c-e9df-b8b7-f0e0-a135b8802329,"Soderblom, Elmer",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,goal,successful,None,GOAL,none,NaN,63.172653,5.282352,63.172653,5.282352,1,1,0,0,1,GR,0,0,0,0,5
1800229,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,1001.030000000,374.0,3365,47,None,None,None,None,None,None,goal,None,None,Goal,none,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,5
1800304,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,1068.670000000,382.0,3440,49,a855a24c-10d7-480c-5f02-f40cacd514f9,"Luff, Matt",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,goal,successful,None,GOAL,none,NaN,48.587357,35.961765,48.587357,35.961765,1,1,0,0,1,GR,0,0,0,0,5
1800305,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,1069.030000000,382.0,3441,49,None,None,None,None,None,None,goal,None,None,Goal,none,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,5

In [14]:
events["event_type"].value_counts()

event_type
pass                      402670
lpr                       338836
reception                 304903
carry                     110362
failedpasslocation         97366
faceoff                    84621
block                      66233
puckprotection             54827
shot                       53971
pressure                   53961
controlledentryagainst     38081
dumpout                    35152
dumpin                     34740
dumpinagainst              32182
whistle                    25397
check                      24992
penalty                    11547
goal                        5667
controlledbreakout          4956
assist                      4793
icing                       4052
penaltydrawn                3765
receptionprevention         2353
deflection                  2047
offside                     2003
solpr                        237
socarry                      237
soshot                       231
sogoal                        76
shootout                      70
teamwithozonright             50
penaltyshot                   40
pslpr                         19
pscarry                       19
sopuckprotection               7
socheck                        1
Name: count, dtype: int64

In [15]:
events[(events["event_type"]=="check") & (events["ozone"]==1)]

,game_id,period,period_time,game_stint,sl_event_id,sequence_id,player_id,player_name,team,team_id,opp_team,opp_team_id,event_type,outcome,flags,description,detail,sl_xg_all_shots,x,y,x_adj,y_adj,has_tracking_data,event_player_tracked,dzone,nzone,ozone,poss_team,dz_possession_start,dz_exit,dz_turnover,potential_end,cum_starts
338,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,368.830000000,47.0,338,5,8bd8e696-4514-a5d5-792b-80b002761f46,"Hirose, Taro",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,check,successful,None,OZ BODY CHK+,body,NaN,73.734420,-39.479410,73.734420,-39.479410,1,1,0,0,1,GR,0,0,1,1,6
461,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,504.030000000,60.0,461,8,015f554a-21c0-99bc-0a31-a176810b40c6,"Shine, Dominik",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,check,successful,None,OZ STICK CHK+,stick,NaN,97.372650,12.323528,97.372650,12.323528,0,0,0,0,1,GR,0,0,1,1,2
1493,00b0366a-95c6-5250-2dae-e3dd5c4198bc,2,304.570000000,172.0,1493,22,4447229a-e693-b7a3-6bbe-f464ae9917c4,"Pyyhtia, Mikael",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,check,successful,None,OZ STICK CHK+,stick,NaN,96.363266,0.250332,96.363266,0.250332,1,1,0,0,1,CLE,0,0,1,1,3
1499,00b0366a-95c6-5250-2dae-e3dd5c4198bc,2,309.770000000,172.0,1499,22,f7d87866-fb2a-6a94-5317-d30145102fef,"Meyer, Carson",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,check,successful,None,OZ STICK CHK+,stick,NaN,71.216220,34.450333,71.216220,34.450333,1,1,0,0,1,CLE,0,0,1,1,3
1625,00b0366a-95c6-5250-2dae-e3dd5c4198bc,2,439.630000000,185.0,1625,23,daa52256-1dc6-fde2-afc0-7599fd3359eb,"Hanas, Cross",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,check,successful,None,OZ STICK CHK+,stick,NaN,-95.257320,-4.276138,95.257320,4.276138,1,0,0,0,1,GR,0,0,1,1,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1800057,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,843.570000000,362.0,3193,45,ad4b002b-5fc6-4cdc-1d16-192ced8c9b16,"Gaudet, Jake",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,check,successful,None,OZ BODY CHK+,body,NaN,-91.741110,31.428326,91.741110,-31.428326,0,0,0,0,1,CLE,0,0,1,1,1
1800217,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,995.930000000,374.0,3353,47,daa52256-1dc6-fde2-afc0-7599fd3359eb,"Hanas, Cross",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,check,successful,None,OZ BODY CHK+,body,NaN,83.793240,-37.970590,83.793240,-37.970590,1,0,0,0,1,GR,0,0,1,1,5
1800254,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,1016.800000000,377.0,3390,49,0753b094-9e2f-976d-85c8-d22a1d280e8d,"Jiricek, David",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,check,successful,None,OZ BODY CHK+,body,NaN,-72.621460,41.494118,72.621460,-41.494118,1,1,0,0,1,CLE,0,0,1,1,1
1800273,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,1035.500000000,377.0,3409,49,6845c1eb-216d-4366-cda0-d3c220357faf,"Del Bel Belluz, Luca",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,check,successful,None,OZ STICK CHK+,stick,NaN,-64.071465,-4.776470,64.071465,4.776470,0,0,0,0,1,CLE,0,0,1,1,2
1800357,ff8386b6-5f9b-4734-00e6-bc8b4c0a4cca,3,1110.970000000,384.0,3493,51,65195a5e-8639-a163-d566-03adc8582060,"Tuomisto, Antti",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,check,successful,None,OZ STICK CHK+,stick,NaN,31.990310,-40.485290,31.990310,-40.485290,1,1,0,0,1,GR,0,0,1,1,0

In [16]:
events.head(341)

,game_id,period,period_time,game_stint,sl_event_id,sequence_id,player_id,player_name,team,team_id,opp_team,opp_team_id,event_type,outcome,flags,description,detail,sl_xg_all_shots,x,y,x_adj,y_adj,has_tracking_data,event_player_tracked,dzone,nzone,ozone,poss_team,dz_possession_start,dz_exit,dz_turnover,potential_end,cum_starts
0,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,0,1,None,None,None,None,None,None,faceoff,None,None,Face-Off,nz,NaN,NaN,NaN,NaN,NaN,1,0,0,0,0,None,0,0,0,0,0
1,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,1,1,8cdcb61e-d733-bde6-a101-ef3140e48149,"L'Esperance, Joel",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,faceoff,failed,"centerfodot, righthandedopponent",NZ FACE OFF-,none,NaN,-0.201431,-0.755550,-0.201431,-0.755550,1,1,0,1,0,GR,0,0,0,0,0
2,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0E-9,1.0,2,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,faceoff,successful,"centerfodot, righthandedopponent",NZ REC FACE OFF+ENTRY,recoveredwithentry,NaN,-0.201431,-0.755550,0.201431,0.755550,1,1,0,1,0,CLE,0,0,0,0,0
3,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.070000000,1.0,3,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,None,F/OFF LPR+ NZ,faceoff,NaN,0.807243,1.257381,-0.807243,-1.257381,1,1,0,1,0,CLE,0,0,0,0,0
4,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,0.130000000,1.0,4,1,dc5a9c10-c8d3-52bc-fd80-b7186f383b34,"McKown, Hunter",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,pass,successful,eastside,NZPASS south+,south,NaN,0.304306,0.845894,-0.304306,-0.845894,1,1,0,1,0,CLE,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,366.970000000,46.0,336,5,90e5f527-993f-a1ac-44b5-9fb226fa6128,"Whelan, Alex",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,failed,None,LPR- DZ,none,NaN,79.266770,-28.414703,-79.266770,28.414703,1,0,1,0,0,CLE,1,0,0,0,6
337,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,368.670000000,47.0,337,5,d54b6c97-2380-f382-7937-732841fca283,"Pearson, Justin",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,lpr,successful,alongboards,LPR FROM SC DZ,none,NaN,76.752075,-40.485290,-76.752075,40.485290,1,0,1,0,0,CLE,0,0,0,0,6
338,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,368.830000000,47.0,338,5,8bd8e696-4514-a5d5-792b-80b002761f46,"Hirose, Taro",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,check,successful,None,OZ BODY CHK+,body,NaN,73.734420,-39.479410,73.734420,-39.479410,1,1,0,0,1,GR,0,0,1,1,6
339,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,368.830000000,47.0,339,5,d54b6c97-2380-f382-7937-732841fca283,"Pearson, Justin",CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,puckprotection,failed,None,DZPUCKPROTECTION-,body,NaN,73.734420,-38.976470,-73.734420,38.976470,1,0,1,0,0,CLE,0,0,0,0,6
340,00b0366a-95c6-5250-2dae-e3dd5c4198bc,1,369.930000000,47.0,340,5,8bd8e696-4514-a5d5-792b-80b002761f46,"Hirose, Taro",GR,6cac12e2-0546-2c1a-689f-ab26d8a6355a,CLE,d7ff41e7-8310-f2ab-3c79-6ad3d1f4f019,lpr,successful,alongboards,BC LPR OZ,none,NaN,64.681470,-39.982353,64.681470,-39.982353,1,1,0,0,1,GR,0,0,1,1,6